### ISSUE TITLE
 Failure to find com.amazonaws:DynamoDBLocal:jar:1.13.6

### ISSUE THREAD

**Issue by chinthakadeshapriya** [madeindra/signal-setup-guide#102]
When I execute the command I get the following error. Please help me to rectify the issue. Os is Ubuntu 20.04
====Errors=====
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.348 s
[INFO] Finished at: 2021-05-29T05:41:43Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project service: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.amazonaws:DynamoDBLocal:jar:1.13.6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :service

**Comment by madeindra** [comment]
Which Maven & Java version is this?

**Comment by chinthakadeshapriya** [comment]
mvn -v
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1045-aws", arch: "amd64", family: "unix

Ubuntu 20.04

**Comment by madeindra** [comment]
Have you modify anything before?

**Comment by chinthakadeshapriya** [comment]
No,  but observed that it is included in services/pom.xml

**Comment by chinthakadeshapriya** [comment]
I tried on 18.04 and the result is same

**Comment by madeindra** [comment]
If you run the command after `dependency`, does the same error occur?

**Comment by chinthakadeshapriya** [comment]
I have executed the following in Ubuntu 18.04

mvn dependency:resolve dependency:resolve-plugins

The result is below:
==============

[INFO] TextSecureServer ................................... SUCCESS [  1.536 s]
[INFO] redis-dispatch ..................................... SUCCESS [  0.279 s]
[INFO] websocket-resources ................................ SUCCESS [  0.653 s]
[INFO] gcm-sender-async ................................... SUCCESS [  0.260 s]
[INFO] service ............................................ FAILURE [  1.339 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.459 s
[INFO] Finished at: 2021-06-09T04:28:34Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project service: Could not resolve dependencies for project org.whispersystems.textsecure:service:jar:5.98.0: The following artifacts could not be resolved: org.whispersystems.textsecure:redis-dispatch:jar:5.98.0, org.whispersystems.textsecure:websocket-resources:jar:5.98.0, org.whispersystems.textsecure:gcm-sender-async:jar:5.98.0: Could not find artifact org.whispersystems.textsecure:redis-dispatch:jar:5.98.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by dotneutron** [comment]
@chinthakadeshapriya I encountered the same error when trying to build `v5.98`. I managed to build `TextSecureServer-5.98.0.jar` with `mvn -e -B -DskipTests package`.

**Comment by chinthakadeshapriya** [comment]
Thanks a lot I got it a success with  your build options

**Comment by chinthakadeshapriya** [comment]
I am closing the thread

**Comment by chinthakadeshapriya** [comment]
I am closing the thread
