### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project websocket-resources

### ISSUE THREAD

**Issue by boykoy96bg** [madeindra/signal-setup-guide#115]
I can't build signal-server version 5.3.1. 
can you help me ?
![error](https://user-images.githubusercontent.com/43708667/122496480-0bc12f80-d016-11eb-8031-2dddb7cb4407.PNG)

**Comment by boykoy96bg** [comment]
[INFO] 
[ERROR] Tests run: 20, Failures: 0, Errors: 19, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] TextSecureServer 1.0 ............................... SUCCESS [  1.844 s]
[INFO] redis-dispatch 5.31 ................................ SUCCESS [  6.613 s]
[INFO] websocket-resources 5.31 ........................... FAILURE [ 10.211 s]
[INFO] gcm-sender-async 5.31 .............................. SKIPPED
[INFO] service 5.31 ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.897 s
[INFO] Finished at: 2021-06-18T09:14:39+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project websocket-resources: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\codejavaproject\Signal-Server-5.31\websocket-resources\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :websocket-resources

**Comment by madeindra** [comment]
Did you build in Windows? Not sure if building in Windows is supported

**Comment by boykoy96bg** [comment]
> Did you build in Windows? Not sure if building in Windows is supported
This could also be an issue. I tried to try with mvn clean install -DskipTests and bed like it worked
