### ISSUE TITLE
Android App Error: .../v1/token/...  404 not found?

### ISSUE THREAD

**Issue by rbellek** [madeindra/signal-setup-guide#29]
![resim](https://user-images.githubusercontent.com/36569057/107103499-f3066900-682e-11eb-87a0-cca387dc5416.png)

## Signal  Server 3.21 & Andorid App Version 4.66.1 ##

Users are created but PIN is not setup correctly. So, we cannot access contact list and send message to others. 

What is the point that we missed? 

Thank you.

**Comment by madeindra** [comment]
@rbellek nothing you missed, the server just doesn't have the code for PIN yet, but you can disable PIN on android

**Comment by rbellek** [comment]
@madeindra thank you for your reply, it makes sense. Do you plan to implement the PIN code for the server in the near future? If you are positive, we looking forward to see your release. Thanks again.

**Comment by madeindra** [comment]
@rbellek Well, it's up to the official Signal Team to implement that. As for now, unfortunately, I have not had any interest in developing a fork of Signal server.

If you are interested in removing the PIN from the Android version, I have written the guide separately here:
https://gist.github.com/madeindra/b5cf85ed337e0d0b19839fa8b3c5520c
