### ISSUE TITLE
Cannot download attachments in Android App using Minio?

### ISSUE THREAD

**Issue by rbellek** [madeindra/signal-setup-guide#32]
We have no issue about uploading images (and other binary files) to the minio server using android app. We double check minio server image files are already uploaded. 

**However, we cannot download images from Android app. Minio return Code: 416**

![416](https://user-images.githubusercontent.com/36569057/107764572-7816e400-6d41-11eb-8e3d-4e74778e8d9c.png)

This is the original source code in Adroid App which causes the problem for minio server. Minio doesn't accept "bytes=#####-" syntax.

<img width="568" alt="offset_" src="https://user-images.githubusercontent.com/36569057/107764677-a8f71900-6d41-11eb-9961-5d8103b978be.png">
 
So we comment that line out to let minio respond the file to download.

<img width="524" alt="original_commented" src="https://user-images.githubusercontent.com/36569057/107764758-cc21c880-6d41-11eb-8496-b53427b33550.png">

It downloads the file, the content of the file is also valid. However, another error code has been occured.

<img width="1069" alt="MAC" src="https://user-images.githubusercontent.com/36569057/107764839-eb205a80-6d41-11eb-9fc3-3d4eba1b82b6.png">

It gives us "MAC doesn't match!" error which is about HMAC-SHA256 algorithm to verify file integrity.

We also try to give full file range with "bytes=0-offset" syntax.

<img width="553" alt="0_offset" src="https://user-images.githubusercontent.com/36569057/107764945-0ee3a080-6d42-11eb-9826-3e7b44236185.png">

The result is same as above. (MAC doesn't match)

**I wonder how can you run Android app and download files using minio?  I couldn't see any fix for this CDN download line in your guide. I believe everybody is going to get the same error if they use MINIO as a CDN S3 server backend. :/**

Thank you.

**Comment by madeindra** [comment]
Need more info. Which version of minio? Did you use the docker with minio from the guide?
Did you modify the server code to support minio? Did you modify the upload or download path on the android?

**Comment by smith1993pro** [comment]
@madeindra hi...
I installed minio and was able to connect to it with a browser(https://minio-server.localhost:9000).
I also changed the server code according to your tutorial.
but i have error:
`Causing: org.apache.http.conn.HttpHostConnectException: Connect to **minio-server.xxx.com:9000** [minio-server.xxx.com/x.x.x.x] failed: Connection refused (Connection refused)
! at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:566)
! at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
! at com.amazonaws.http.conn.$Proxy47.connect(Unknown Source)
! at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
! at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1238)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
! ... 77 common frames omitted
! Causing: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to **minio-server.xxx.com:9000** [minio-server.xxx.com/x.x.x.x] failed: Connection refused (Connection refused)`


my config:
awsAttachments:
  accessKey:   xxxxxxxxxxxxxxxxx
  accessSecret: xxxxxxxxxxxxxxxxxx
  bucket:       mybucket
  region:       us-east-1 
  endpoint:     https://minio-server.localhost:9000

cdn:
  accessKey:    xxxxxxxxxxxxxxxxx
  accessSecret: xxxxxxxxxxxxxxxxxx
  bucket:       mybucket 
  region:       us-east-1
  endpoint:     https://minio-server.localhost:9000 

I use Signal Server v3.21 & Signal Android v4.66.1

**Comment by rbellek** [comment]
@madeindra 

**1) Which version of minio?** 

- minio version: minio/minio:RELEASE.2021-02-07T01-31-02Z 
- Sinal Server : :v2.92.1 
- Android App : 4.53.6


**2) Did you use the docker with minio from the guide?**

- Yes, it is the same docker file. (We test both localhost and our domain, the same error)

**3) Did you modify the server code to support minio?** 

- Yes, we follow the modification steps in the guide for the signal server code (and also Android App).

**4) Did you modify the upload or download path on the android?**

- Yes, we do.
- Generated URLs are valid, we can download files using browsers.

---

We can download files from minio by using the same URL. [https://minio-signal.OUR_DOMAIN.com/woramessenger/6267187476192576722](https://minio-signal.OUR_DOMAIN.com/woramessenger/6267187476192576722)  (I can share the real URL by email if you wish).   Here is a sample file just downloaded from the minio server.

![file_begin](https://user-images.githubusercontent.com/36569057/107852581-9f91ad80-6e22-11eb-90cc-6e302f704dc2.png)

![file_end](https://user-images.githubusercontent.com/36569057/107852585-a3bdcb00-6e22-11eb-817f-786f01bcb6e5.png)


A screenshot from the Android App.

<img width="1399" alt="ss" src="https://user-images.githubusercontent.com/36569057/107852602-b506d780-6e22-11eb-84e3-f980c15a6837.png">

**Comment by madeindra** [comment]
@smith1993pro is your problem rrlated to this issue? If not, please open another issue. As for connection rrfused, it could be a mistake in credential, please recheck it.

@rbellek I've not yet experience 416 error, did you use nginx or apache? Can you share your configuration?

**Comment by rbellek** [comment]
@madeindra 

**1) ... did you use nginx or apache?** 

No, we use Treaffic over kubernetes, but we also try it using nginx, the result is the same error. We believe that the error is not related to the reverse proxy.

**2) Can you share your configuration?**

I can share you the postman script. You may try it by yourself. The offset range is problematic. 

https://www.getpostman.com/collections/40183a7cc0227804e48b 

We just upload the file into the [https://play.minio.io:9000/minio/](https://play.minio.io:9000/minio/) to proof the misusage of offset-range syntax from the original code. 

The byte range value is generated from the original Android app code. 

![original](https://user-images.githubusercontent.com/36569057/107855677-c953d000-6e34-11eb-8af2-22165f4629fe.png)

We decrease the offset value for just brainstorming.

![modified](https://user-images.githubusercontent.com/36569057/107855715-f902d800-6e34-11eb-9370-dcb24ea05a3f.png)


This is the proof that the logic in the original code is not working with minio or the offset value is miscalculated :( 
If these details is not clear for you I can supply more. Thank you.

**Comment by madeindra** [comment]
If this is generated by the code, can you try other mobile version? Maybe 4.66.1 could work, but if not, I'm not sure it's the android that caused this error

**Comment by rbellek** [comment]
@madeindra We have solved the problem with following changes. Multipart form data is not suitable for minio PUT request because it writes form data into the attachment file, so Android App cannot verify HMAC SHA256 and also cannot open the image. We just remove the multipart data and put them all into headers. Now, we can send and receive images successfully. One problem left, we couldn't upload the minio server while policy is set to read-only mode. I think credential information is not valid. This is another issue topic, by the way. Thanks for your attention.

This is the code patch for anyone who got the same error.

libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java 

```diff
---
 private byte[] uploadToCdn0(String path, String acl, String key, String policy, String algorithm,
                              String credential, String date, String signature,
                              InputStream data, String contentType, long length,
                              OutputStreamFactory outputStreamFactory, ProgressListener progressListener,
                              CancelationSignal cancelationSignal)
      throws PushNetworkException, NonSuccessfulResponseCodeException
  {
    ConnectionHolder connectionHolder = getRandom(cdnClientsMap.get(0), random);
    OkHttpClient     okHttpClient     = connectionHolder.getClient()
                                                        .newBuilder()
                                                        .connectTimeout(soTimeoutMillis, TimeUnit.MILLISECONDS)
                                                        .readTimeout(soTimeoutMillis, TimeUnit.MILLISECONDS)
                                                        .build();

DigestingRequestBody file = new DigestingRequestBody(data, outputStreamFactory, contentType, length, progressListener, cancelationSignal, 0);
 
-    RequestBody requestBody = new MultipartBody.Builder()
-                                               .setType(MultipartBody.FORM)
-                                               .addFormDataPart("acl", acl)
-                                               .addFormDataPart("key", key)
-                                               .addFormDataPart("policy", policy)
-                                               .addFormDataPart("Content-Type", contentType)
-                                               .addFormDataPart("x-amz-algorithm", algorithm)
-                                               .addFormDataPart("x-amz-credential", credential)
-                                               .addFormDataPart("x-amz-date", date)
-                                               .addFormDataPart("x-amz-signature", signature)
-                                               .addFormDataPart("file", "file", file)
-                                               .build();
-

+  Request.Builder request = new Request.Builder()
+            .url(connectionHolder.getUrl() + "/" + key)
+            .method("PUT", file)
+            .addHeader("Content-Type", "application/octet-stream")
+            .addHeader("acl", acl)
+            .addHeader("key", key)
+            .addHeader("policy", policy)
+            .addHeader("bucket", "attachments")
+            .addHeader("x-amz-algorithm", algorithm)
+            .addHeader("x-amz-credential", credential)
+            .addHeader("x-amz-date", date)
+            .addHeader("x-amz-signature", signature);
 
     if (connectionHolder.getHostHeader().isPresent()) {
       request.addHeader("Host", connectionHolder.getHostHeader().get());
```
