### ISSUE TITLE
iOS version was unable to connect to the internet

### ISSUE THREAD

**Issue by yang093** [madeindra/signal-setup-guide#45]
**Server Version :** (Server v3.21)

**Client Version :** (iOS version)

I was able to make Android version can run with my custom signal server. However, for iOS version, I got the error below at the input phone number step:

OnboardingController.swift:714 requestVerification(fromViewController:isSMS:completion:)]: Error: taskError(task: LocalDataTask <604ECD66-14BE-49EF-A590-E254E85298AC>.<3>, underlyingError: Error Domain=SignalServiceKit.TSNetworkManager Code=0 "Signal was unable to connect to the internet. Please try again." UserInfo={NSUnderlyingError=0x60000265bb10 {Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://testsignal.xxx/v1/accounts/sms/code/+84765101751?client=ios, NSErrorFailingURLKey=https://testsignal.xxx/v1/accounts/sms/code/+84765101751?client=ios, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <604ECD66-14BE-49EF-A590-E254E85298AC>.<3>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <604ECD66-14BE-49EF-A590-E254E85298AC>.<3>, NSLocalizedDescription=cancelled}}, NSLocalizedDescription=Signal was unable to connect to the internet. Please try again., NSLocalizedRecoverySuggestion=Please check if you are online and try again.})

I tried to update textsecure.cer file but with no luck

@madeindra did you encounter this issue before?

**Comment by madeindra** [comment]
@yang093 Which version of ios? Did you use simulator / real device?

**Comment by yang093** [comment]
@madeindra I re-generate the cer file and convert to correct format and it works on simulator. However, I got crashes after input phone number step. I will open a new ticket for this
