### ISSUE TITLE
error java.lang.IllegalArgumentException: org.signal.zkgroup.InvalidInputException: Length of array supplied was 763 expected 723

### ISSUE THREAD

**Issue by afyfe** [madeindra/signal-setup-guide#46]
Hi

I hope someone can help

generating the zxparams

 java -jar /GIT/Signal-Server/service/target/TextSecureServer-3.21.jar zkparams

gives me private and publick key

enter them into config.yaml, whne i run the jar server i get the error ...

tried mutliple times !

help

**Comment by madeindra** [comment]
@afyfe Please post your error message here

**Comment by afyfe** [comment]
Hi, the error is

java.security.InvalidKeyException: Key must not be null
[5.543s][info][class,load] java.lang.StackTraceElement$HashedModules
source: jrt:/java.base
        at
java.base/sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:118)
        at
java.base/sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:111)
        at
java.base/sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:103)
        at
java.base/java.security.Signature$Delegate.tryOperation(Signature.java:1308)
        at
java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1257)
        at
java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1354)
        at java.base/java.security.Signature.initSign(Signature.java:636)
        at
org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.testKeyIsValidForSigning(CanonicalRequestSigner.java:76)
        at
org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.initializeRsaSigningKey(CanonicalRequestSigner.java:65)
        at
org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.<init>(CanonicalRequestSigner.java:23)
        at
org.whispersystems.textsecuregcm.controllers.AttachmentControllerV3.<init>(AttachmentControllerV3.java:46)
        at
org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:304)
        at
org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:151)
        at
io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at
io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at
org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:406)
[5.544s][info][class,load]
io.dropwizard.Application$$Lambda$527/0x00000008404d6440 source:
io.dropwizard.Application

**Comment by madeindra** [comment]
@afyfe You have an empty value for gcp key

**Comment by afyfe** [comment]
i have a value...

in my config:

gcpAttachments: # gcp storage configuration
  domain: safesignals.local
  email: ***@***.***
  maxSizeInBytes: 1000000
  pathPrefix: /
  rsaSigningKey: /correct-path-to-key/gcpnew.key


and in the referneced file the key is there.


thank for the help

**Comment by afyfe** [comment]
Any ideas?

help is very much appreciated !

**Comment by madeindra** [comment]
@afyfe In my experience, it's better to paste the string of the RSA key rather than the path.
Paste it with the new line substituted with `\n`

**Comment by afyfe** [comment]
Thank you, that worked for me
