### ISSUE TITLE
I can't send message on android because I can't find any contact list

### ISSUE THREAD

**Issue by pyDjangoDev** [madeindra/signal-setup-guide#58]
Hi, @madeindra
I followed your instruction and my signal server is working.
And I build the android version.
when searching contact, android app requests /v1/attestation/********** to signal server.
but signal server responds 404

and /v1/token/********, it's 404 too
I know they are the issues related to CDS and pin.
Please help me.

**Comment by madeindra** [comment]
@pyDjangoDev First install? Rrstart the mobile app first, it's normal
