### ISSUE TITLE
Signal message is delivered from A to B. But not delivered from B to A

### ISSUE THREAD

**Issue by pyDjangoDev** [madeindra/signal-setup-guide#61]
**Server Version :** (Server v3.21)
**Client Version :** (Android v4.66.1)
Hello @madeindra.
First, Thank you for this full guide.
As you can see from the above error, The message is delivered from A to B but I can't send the message from B to A.
What do I need to modify?
Please help me.
Thank you.

**Comment by madeindra** [comment]
@pyDjangoDev Check if you have generated Unidentified Sender Trust Root correctly, see if the correct value is pasted in build.gradle

**Comment by pyDjangoDev** [comment]
@madeindra 
Thanks for your help.
The chat is working well.
The audio/video call is not working.
If A clicks on the Audio call Button to B and B click on the Answer Button to respond, It shows me "Answering"
Please help me.

**Comment by madeindra** [comment]
@pyDjangoDev Any notification when any call come? Please answer the call only when the call screen show by itself

**Comment by pyDjangoDev** [comment]
Yes. There is a notification when any call comes. If I click on the notification, the call screen is showed.
not by itself. so I click the "Answer" button, It only shows me "Answering".

**Comment by pyDjangoDev** [comment]
@madeindra 
![image_2021_04_13T18_24_11_387Z](https://user-images.githubusercontent.com/61251512/114602751-8c3b7b00-9cc9-11eb-9a2e-c4b498d04a04.png)
When start to call, the calling screen has appeared, but it said "Network failed" and disappeared.
But the app is still ringing and the notification is still alive.
![image_2021_04_13T18_28_51_187Z](https://user-images.githubusercontent.com/61251512/114602870-ad9c6700-9cc9-11eb-81fc-a4a1e9bdfa34.png)
When I click the notification, it shows a black screen.
![image_2021_04_13T18_29_17_190Z](https://user-images.githubusercontent.com/61251512/114602965-c3119100-9cc9-11eb-8e3b-e160578cc471.png)
On this black screen, when I press back, it is floated, and I can't close it.
![image_2021_04_13T18_29_58_655Z](https://user-images.githubusercontent.com/61251512/114603070-dcb2d880-9cc9-11eb-92af-99ad05644fb0.png)
Here is the log screen.
![image_2021_04_13T18_30_11_636Z](https://user-images.githubusercontent.com/61251512/114603119-ee947b80-9cc9-11eb-9c21-ed27676a96b5.png)

And Here are the signal server conf, coTurn conf, and logs.
![2021-04-14_02-36](https://user-images.githubusercontent.com/61251512/114603444-4f23b880-9cca-11eb-8b42-c2cb1065beac.png)
![2021-04-14_02-39](https://user-images.githubusercontent.com/61251512/114603681-9ca02580-9cca-11eb-9d0f-83608fb7e035.png)
![2021-04-14_02-29](https://user-images.githubusercontent.com/61251512/114603710-a3c73380-9cca-11eb-8cbc-1723eb571151.png)

What am I missing?

**Comment by pyDjangoDev** [comment]
I am using AWS EC2 and the security group to allow the ports.
![scg](https://user-images.githubusercontent.com/61251512/114524916-37bbdf80-9c78-11eb-8e20-a4500f522a5c.png)

**Comment by madeindra** [comment]
@pyDjangoDev Your config doesn't show here.
Which port did you use for coturn? Try changing it to common used port like `8000`, `8080`, `8001`, or `8081` whichever isn't being used by the server

**Comment by pyDjangoDev** [comment]
Thank you. I already solved that point myself.

**Comment by madeindra** [comment]
That's great
