### ISSUE TITLE
 The requested metadata is not found at

### ISSUE THREAD

**Issue by Jonnter** [madeindra/signal-setup-guide#66]
**Server Version :** signal-server-5.xx

hello:
 The following error was reported during the startup process. Could you please check the reason

[root@ip-172-31-39-220 service]# java -jar target/TextSecureServer-5.51.jar server config/config.yml
INFO  [2021-04-19 14:54:31,024] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-04-19 14:54:31,027] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-04-19 14:54:31,096] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
WARN  [2021-04-19 14:54:32,462] io.dropwizard.lifecycle.setup.ExecutorServiceBuilder: Parameter 'maximumPoolSize' is conflicting with unbounded work queues
WARN  [2021-04-19 14:54:32,463] io.dropwizard.lifecycle.setup.ExecutorServiceBuilder: Parameter 'maximumPoolSize' is conflicting with unbounded work queues
INFO  [2021-04-19 14:54:32,486] com.amazonaws.internal.DefaultServiceEndpointBuilder: {appconfig, ap-southeast-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'appconfig.ap-southeast-1.amazonaws.com'.
WARN  [2021-04-19 14:54:32,511] org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager: Error retrieving initial dynamic configuration
! com.amazonaws.SdkClientException: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:89)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
! at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
! at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
! at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)
! at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)
! at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)
! at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)
! at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:165)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.doInvoke(AmazonAppConfigClient.java:2338)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.invoke(AmazonAppConfigClient.java:2305)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.invoke(AmazonAppConfigClient.java:2294)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.executeGetConfiguration(AmazonAppConfigClient.java:976)
! at com.amazonaws.services.appconfig.AmazonAppConfigClient.getConfiguration(AmazonAppConfigClient.java:946)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.retrieveDynamicConfiguration(DynamicConfigurationManager.java:94)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.retrieveInitialDynamicConfiguration(DynamicConfigurationManager.java:116)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.start(DynamicConfigurationManager.java:68)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:330)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:185)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:540)

**Comment by pyDjangoDev** [comment]
which one of the guides did you follow?

**Comment by madeindra** [comment]
@Jonnter have you created an AWS Account?

**Comment by Jonnter** [comment]
> 您遵循了哪一项指南？

5.x.x 最新的master

**Comment by Jonnter** [comment]
> @Jonnter您创建了一个AWS账户吗？

There has been a aws Account，The required configuration is complete

accessKey: AKIA3NWGTIUTX2
  accessSecret: nU150Q4/5vtPjUT/zEoarsq0cI81Y/7heJY
  bucket: st-s3
  region: ap-sot-1

**Comment by madeindra** [comment]
@Jonnter You should not post your credential online, please edit it and change your IAM credential.
Regardless, try creating all bucket & queue needed before running the server

**Comment by Jonnter** [comment]
> credential online

credential online The content is abridged, thank you；
creating all bucket & queue It's already created in AWS。
java -jar target/TextSecureServer-5.51.jar Create with this command?

**Comment by madeindra** [comment]
@Jonnter
creating jar file is done using
```
mvn clean install
mvn -e -B package
```

running is done using
```
java -jar TextSecureServer-5.51.jar server config.yml
```

**Comment by Jonnter** [comment]
mvn clean install
mvn -e -B package
All executed, report redis error
[INFO] TextSecureServer 1.0 ............................... SUCCESS [  4.592 s]
[INFO] redis-dispatch 5.54 ................................ FAILURE [  4.295 s]
[INFO] websocket-resources 5.54 ........................... SKIPPED
[INFO] gcm-sender-async 5.54 .............................. SKIPPED
[INFO] service 5.54 ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.183 s
[INFO] Finished at: 2021-04-21T13:08:50+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:analyze-only (analyze) on project redis-dispatch: Dependency problems found -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :redis-dispatch

**Comment by madeindra** [comment]
@Jonnter  Yeah after it fail, try running `mvn -e -B package` it works in my experience

**Comment by Jonnter** [comment]
A new error occurred at runtime

**Comment by madeindra** [comment]
@Jonnter Has the jar been completed successfully? 

If yes, then that's the end of the support provided in this version, I have not yet reached success runtime so please wait or experiment on it.

**Comment by Jonnter** [comment]
Port and service started successfully, port 8080 reported 404

**Comment by madeindra** [comment]
That's great, but sorry I can't help, i have not reach that part, thus I don't know about what might cause the error
