### ISSUE TITLE
Minio server

### ISSUE THREAD

**Issue by Selciuz** [madeindra/signal-setup-guide#70]
**Server Version :** (Server v3.21)

Hello, i was wondering how to change the AWS SQS in config.yml with my own MinIO server, didn't find any step about it in the tutorial.
I'm using localstack for SQS queue for now combined with MinIO for S3 and CloudFront but i'm not sure if it works correctly because i didn't setup CDS so i can't test texting "yet" and I've read that LocalStack works only offline so i have doubts about it.

**Comment by madeindra** [comment]
If you don't use CDS, then you can ignore SQS.
SQS is a message queue, it's not the same with MinIO which is a File Storage, you can't and won't be able to subtitute SQS with MinIO.
