### ISSUE TITLE
Signal Server V3.21 can compatible with Signal Android V5.9?

### ISSUE THREAD

**Issue by taftazaniadi** [madeindra/signal-setup-guide#71]
**Server Version :** (Server v3.21)

**Android Signal Version:** (Signal Android v5.9)

## Describe what are you trying to achieve

I want Signal Server can compatible with Signal App V5.9..

## Describe the issue that you face

Signal App V5.9 cannot read the API from Signal Server V3.21..

## Logs

```
W/ContactSelectionListFra: null
   org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=404, message=Not Found, url=http://x.japri.chat:8080/v1/attestation/c98e00a4e3ff977a56afefe7362a27e4961e4f19e211febfbb19b897e6b80b15}
```

## Screenshots

![WhatsApp Image 2021-04-26 at 2 58 30 PM](https://user-images.githubusercontent.com/38445835/116347224-03b6f180-a816-11eb-8e22-95ecc6e46f94.jpeg)

**Comment by madeindra** [comment]
It's asking for CDS endpoint which you have not implement, it's optional by the way

**Comment by taftazaniadi** [comment]
Where i can implement CDS endpoint?

**Comment by madeindra** [comment]
For now I have not tried implementing it because the need of specific hardware, but there's a link on main readme that goes to a guide written by a signal community user
