### ISSUE TITLE
error messageCache while running server

### ISSUE THREAD

**Issue by JonnyX11** [madeindra/signal-setup-guide#73]
-------------------------
johhny@server:~/Signal-Server$ java -jar service/target/TextSecureServer-5.30.jar server service/config/config.yml 
INFO  [2021-04-29 10:35:47,865] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-04-29 10:35:47,868] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-04-29 10:35:47,969] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
java.lang.NumberFormatException: For input string: "messageCache"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.lettuce.core.RedisURI.buildRedisUriFromUri(RedisURI.java:692)
	at io.lettuce.core.RedisURI.create(RedisURI.java:286)
	at io.lettuce.core.RedisURI.create(RedisURI.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.whispersystems.textsecuregcm.redis.FaultTolerantRedisCluster.<init>(FaultTolerantRedisCluster.java:67)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:302)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)

The messageCache:

messageCache:
  cluster:
    urls:
      - redis://127.0.0.1:6379/messageCache

Thanks

**Comment by madeindra** [comment]
try
```
messageCache:
cluster:
urls:
- redis://127.0.0.1:6379
```

**Comment by JonnyX11** [comment]
NFO  [2021-04-29 12:49:42,100] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-04-29 12:49:42,103] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-04-29 12:49:42,171] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
java.lang.IllegalArgumentException: URI scheme must not be null
	at io.lettuce.core.internal.LettuceAssert.notNull(LettuceAssert.java:71)
	at io.lettuce.core.RedisURI.buildRedisUriFromUri(RedisURI.java:651)
	at io.lettuce.core.RedisURI.create(RedisURI.java:286)
	at io.lettuce.core.RedisURI.create(RedisURI.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.whispersystems.textsecuregcm.redis.FaultTolerantRedisCluster.<init>(FaultTolerantRedisCluster.java:67)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:304)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)


pubsub:
  url: redis://127.0.0.1:6379/cache
  replicaUrls:
    - redis://127.0.0.1:6379/cacheReplica

**Comment by JonnyX11** [comment]
I solved it, now the big issue :)

INFO  [2021-04-29 13:10:07,250] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-04-29 13:10:07,253] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-04-29 13:10:07,322] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
WARN  [2021-04-29 13:10:17,056] com.amazonaws.util.EC2MetadataUtils: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
! java.net.SocketTimeoutException: connect timed out
! at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
! at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
! at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
! at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
! at java.base/java.net.Socket.connect(Socket.java:609)
! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
! at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
! at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
! ... 22 common frames omitted
! Causing: com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
! at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
! at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
! at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
! at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
! at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
! at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
! at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
! at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:475)
! at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:458)
! at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
! at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.<init>(DynamicConfigurationManager.java:46)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.<init>(DynamicConfigurationManager.java:46)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)

**Comment by JonnyX11** [comment]
check this ...

INFO  [2021-04-29 13:24:44,524] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-04-29 13:24:44,527] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-04-29 13:24:44,585] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for  every 1m
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.<init>(DynamicConfigurationManager.java:46)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
	at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
WARN  [2021-04-29 13:24:54,281] com.amazonaws.util.EC2MetadataUtils: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
! java.net.SocketTimeoutException: connect timed out
! at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
! at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
! at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
! at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
! at java.base/java.net.Socket.connect(Socket.java:609)
! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
! at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
! at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
! ... 22 common frames omitted
! Causing: com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
! at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
! at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
! at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
! at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
! at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
! at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
! at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
! at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:475)
! at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:458)
! at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
! at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.<init>(DynamicConfigurationManager.java:46)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)
	at io.dropwizard.Application.run(Application.java:94)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)

**Comment by madeindra** [comment]
Have you setup your AWS dependency?

**Comment by JonnyX11** [comment]
Can you please specify what to do for support this locally ?

How to change the address of AWS (Dynamodb) to 127.0.0.1 ?

Thanks!

**Comment by madeindra** [comment]
I've not yet got into that part, I can't help too much on things that have not yet supported in this project, sorry about that.

**Comment by JonnyX11** [comment]
So how did you make it works ?

**Comment by madeindra** [comment]
By trying it, but i have not try

**Comment by JonnyX11** [comment]
Did you success to make it works other way on server and client?

**Comment by madeindra** [comment]
no

**Comment by JonnyX11** [comment]
you are our mentor so we hope you will sucess to make it works server 5.XX and clients android and iOS :)

**Comment by madeindra** [comment]
Thanks, i will try

**Comment by taftazaniadi** [comment]
> I solved it, now the big issue :)
> 
> INFO [2021-04-29 13:10:07,250] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
> INFO [2021-04-29 13:10:07,253] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
> INFO [2021-04-29 13:10:07,322] io.micrometer.core.instrument.push.PushMeterRegistry: publishing metrics for every 1m
> WARN [2021-04-29 13:10:17,056] com.amazonaws.util.EC2MetadataUtils: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint:
> ! java.net.SocketTimeoutException: connect timed out
> ! at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
> ! at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> ! at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> ! at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> ! at java.base/java.net.Socket.connect(Socket.java:609)
> ! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
> ! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
> ! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
> ! at java.base/sun.net.www.http.HttpClient.(HttpClient.java:242)
> ! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
> ! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
> ! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
> ! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
> ! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
> ! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
> ! at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
> ! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
> ! ... 22 common frames omitted
> ! Causing: com.amazonaws.SdkClientException: Failed to connect to service endpoint:
> ! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
> ! at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
> ! at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
> ! at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
> ! at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
> ! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
> ! at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
> ! at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
> ! at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
> ! at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
> ! at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
> ! at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:475)
> ! at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:458)
> ! at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
> ! at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
> ! at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.(DynamicConfigurationManager.java:46)
> ! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
> ! at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
> ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
> ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
> ! at io.dropwizard.cli.Cli.run(Cli.java:78)
> ! at io.dropwizard.Application.run(Application.java:94)
> ! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)
> com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
> at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
> at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
> at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncCfiklientBuilder.java:46)
> at org.whispersystems.textsecuregcm.storage.DynamicConfigurationManager.(DynamicConfigurationManager.java:46)
> at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:315)
> at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:181)
> at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
> at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
> at io.dropwizard.cli.Cli.run(Cli.java:78)
> at io.dropwizard.Application.run(Application.java:94)
> at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:522)

How to fixed this problem? @JonnyX11

**Comment by ankingcodes** [comment]
@JonnyX11 - how did you fix the issue mentioned https://github.com/madeindra/signal-setup-guide/issues/73#issuecomment-829213646
