### ISSUE TITLE
Error: Unable to initialize main class org.whispersystems.textsecuregcm.WhisperServerService

### ISSUE THREAD

**Issue by taftazaniadi** [madeindra/signal-setup-guide#78]
**Server Version :** (Server v5.71)
**Ubuntu Version :** (Ubuntu 18.04)
**Java Version :** (Java v11)

## Describe the issue that you face

I've got some problem when i execute ```java -jar service/target/TextSecureServer-5.71.jar zkparams```..

## Logs

```
tafta@tafta:~/Signal-Server$ java -jar service/target/TextSecureServer-5.71.jar zkparams
Error: Unable to initialize main class org.whispersystems.textsecuregcm.WhisperServerService
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
```

## Screenshots

![image](https://user-images.githubusercontent.com/38445835/117802271-7c3e9900-b27f-11eb-9691-9a0090a09380.png)

**Comment by madeindra** [comment]
Have you done any modification to the project?

**Comment by taftazaniadi** [comment]
Yes, i 've done to modify the project..

**Comment by madeindra** [comment]
I cannot help if you modify anything outside of this guide coverage, there might be some breaking change that needs to be addressed.

Did it work before the modification?

**Comment by taftazaniadi** [comment]
I'm just modify for change AWS to MinIO, when i build server that error is showing..

**Comment by madeindra** [comment]
It indicate the class is not found, check the code again

**Comment by taftazaniadi** [comment]
Alright..

I'll check the code again..
